name: BlazorNet8

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install WASM Tools Workload
        run: dotnet workload install wasm-tools

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Build
        run: dotnet build --no-restore

      - name: Publish BlazorNet8
        run: dotnet publish src/BlazorNet8/BlazorNet8.csproj -c Release -o release --nologo      

      - name: Publish BlazorNet8.Api
        run: dotnet publish src/BlazorNet8.Api/BlazorNet8.Api.csproj -c Release -o api/release --nologo

      - name: Upload BlazorNet8
        uses: actions/upload-artifact@v3.1.3
        with:
          path: /home/runner/work/BlazorNet8/BlazorNet8/release/  
     
      - name: Upload BlazorNet8
        uses: actions/upload-artifact@v3.1.3
        with:
          path: /home/runner/work/BlazorNet8/BlazorNet8/api/release/  

